name: Build Yemen4G APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PYTHONFORANDROID_PREREQUISITES_INSTALL_INTERACTIVE: "0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            automake \
            libltdl-dev \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            libncurses5-dev \
            libtinfo6 \
            cmake \
            git \
            zip \
            unzip \
            gettext \
            autopoint

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade buildozer

      - name: Clean previous Buildozer files
        run: |
          rm -rf .buildozer
          rm -rf "$HOME/.buildozer"

      - name: Prepare Buildozer
        run: |
          buildozer android p4a -- --help

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Yemen4G
          path: bin/*.apk
